# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./tp/server/docker-compose.yml"
        down-flags: "--volumes"
        services: |
          postgres
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'tp/server/package-lock.json'
    - run: cd tp/server && npm ci
    - run: cd tp/server && npm run db:create:test
    - run: cd tp/server && npm run db:migrate:test
    - run: cd tp/server && npm test:it
    - run: cd tp/client && npm ci
    - run: cd tp/client && npm test:unit